export const QUESTIONS = [
	"Who&apos;s the bigger risk-taker: {A} vs {B}?",
	"Bolder under pressure: {A} vs {B}?",
	"More likely to get away with a lie: {A} vs {B}?",
	"King of the hot take: {A} vs {B}?",
	"Bigger shameless flirt: {A} vs {B}?",
	"Who'd survive prison longer: {A} vs {B}?",
	"Who gets away with trouble more often: {A} vs {B}?",
	"Most legendary at 3am: {A} vs {B}?",
	"Better wingman on a wild night: {A} vs {B}?",
	"More likely to ghost the group: {A} vs {B}?",
	"Who would start a bar fight: {A} vs {B}?",
	"Who&apos;d win in a roast battle: {A} vs {B}?",
	"Who cracks under interrogation faster: {A} vs {B}?",
	"Who overshares the most: {A} vs {B}?",
	"Who&apos;s unfiltered to the point of danger: {A} vs {B}?",
	"Messier after a breakup: {A} vs {B}?",
	"More likely to embarrass themselves in public: {A} vs {B}?",
	"Who has the most questionable internet history: {A} vs {B}?",
	"Least likely to get married first: {A} vs {B}?",
	"Who&apos;s more likely to accidentally leak all the group&apos;s secrets: {A} vs {B}?",
	"Who&apos;s better at keeping a scandal under wraps: {A} vs {B}?",
	"Wildest party story: {A} vs {B}?",
	"More likely to DM someone famous: {A} vs {B}?",
	"Which one is more likely to go viral for the wrong reasons: {A} vs {B}?",
	"Who&apos;s tried weirder things: {A} vs {B}?",
	"Confidence level after a few drinks: {A} vs {B}?",
	"Who talks a big game but bails last second: {A} vs {B}?",
	"Which one would date a friend&apos;s ex: {A} vs {B}?",
	"Who gets away with saying wild stuff: {A} vs {B}?",
	"Who&apos;s more likely to lose all their money gambling: {A} vs {B}?"
  ];
  
  
