export const QUESTIONS = [
	"You need a last-minute presentation buddy—who do you ask: {A} or {B}?",
	"Your laptop dies; who do you borrow a charger from: {A} or {B}?",
	"You&rsquo;re forming a quiz team—who gets the captain armband: {A} or {B}?",
	"Who helps you rehearse a 2-minute pitch: {A} or {B}?",
	"You&rsquo;re late to a meeting—who do you text to cover your intro: {A} or {B}?",
	"Who do you trust to take meeting notes for the group: {A} or {B}?",
	"You must pick a spokesperson for your table—{A} or {B}?",
	"Who would you pair with for a brainstorming sprint: {A} or {B}?",
	"There&rsquo;s a schedule clash—who helps you rearrange calmly: {A} or {B}?",
	"You need a quick tutorial (tool/app) in 10 minutes—{A} or {B}?",
	"Who do you ask to proofread a short email before you send: {A} or {B}?",
	"Team lunch picker—who chooses a place everyone likes: {A} or {B}?",
	"You lost your badge/ID—who helps you sort it fast: {A} or {B}?",
	"Group photo time—who gets everyone organized: {A} or {B}?",
	"You need a practice audience for a demo—{A} or {B}?",
	"Snack run for the group—who gets the order right: {A} or {B}?",
	"You have two tasks to delegate—who will balance fairly: {A} or {B}?",
	"Icebreaker host for a new group—{A} or {B}?",
	"You forgot stationery—who probably has a spare: {A} or {B}?",
	"A tiny misunderstanding needs smoothing—who mediates: {A} or {B}?",
	"It&rsquo;s whiteboard time—who keeps the notes tidy: {A} or {B}?",
	"You need a calm partner for an escape-room puzzle—{A} or {B}?",
	"Coffee queue is long—who keeps spirits up: {A} or {B}?",
	"You must choose a timekeeper—{A} or {B}?",
	"Two options look good—who helps you decide: {A} or {B}?",
	"You&rsquo;re making a quick how-to guide—who co-authors: {A} or {B}?",
	"Printer jam! Who actually fixes it: {A} or {B}?",
	"You need a playlist for a chill session—{A} or {B}?",
	"Mildly awkward ice call—who volunteers to go first: {A} or {B}?",
	"You want constructive feedback, short and kind—{A} or {B}?",
	"There&rsquo;s a group order to manage—who tracks everyone&rsquo;s items: {A} or {B}?",
	"You forgot names; who discreetly reminds you: {A} or {B}?",
	"You need a 5-minute training buddy—{A} or {B}?",
	"Logistics lead for a small outing—{A} or {B}?",
	"You&rsquo;re assembling slides—who helps polish formatting: {A} or {B}?",
	"End-of-day recap—who summarizes clearly: {A} or {B}?",
	"You&rsquo;re picking a neutral tiebreaker—{A} or {B}?",
	"You need a countdown hype person—{A} or {B}?",
	"Someone to keep secrets like a birthday plan—{A} or {B}?",
	"You&rsquo;re choosing a teammate for a quick puzzle—{A} or {B}?",
	"You need a calm voice on a call—{A} or {B}?",
	"Who remembers tiny details better: {A} or {B}?",
	"You want to learn a shortcut—who teaches best: {A} or {B}?",
	"A shared doc is messy—who cleans it up: {A} or {B}?",
	"You&rsquo;re setting a group photo caption—who writes it: {A} or {B}?",
	"You need someone to start a round of applause—{A} or {B}?",
	"Choosing a fair randomizer—who spins the wheel: {A} or {B}?",
	"You&rsquo;re booking a table—who confirms headcount well: {A} or {B}?",
	"Quick icebreaker question picker—{A} or {B}?",
	"Two people talk at once—who gently referees: {A} or {B}?",
	"Choosing a calm driver for a short ride—{A} or {B}?",
	"You need to find a lost item fast—{A} or {B}?",
	"Team mascot name brainstorm—who leads: {A} or {B}?",
	"You want a fair coin-flip alternative—who suggests one: {A} or {B}?",
	"You&rsquo;re coordinating a shared checklist—{A} or {B}?",
	"Who&rsquo;s better at remembering birthdays: {A} or {B}?",
	"You need a quick group selfie—who holds the phone: {A} or {B}?",
	"Choosing a neutral background for a call—{A} or {B}?",
	"You&rsquo;re drafting house rules for a game—{A} or {B}?",
	"The room is too quiet—who starts light chat: {A} or {B}?",
	"You must send a polite reminder—who words it best: {A} or {B}?",
	"You need someone to manage timeboxes—{A} or {B}?",
	"Picking a simple team name—{A} or {B}?",
	"You need a gentle nudge to stay on task—{A} or {B}?",
	"Group stretch leader—{A} or {B}?",
	"Choosing a neutral meeting time—{A} or {B}?",
	"You want to split into pairs fairly—who handles it: {A} or {B}?",
	"Setting up a shared calendar invite—{A} or {B}?",
	"You&rsquo;re ordering snacks—who balances sweet/savory: {A} or {B}?",
	"Selecting a background image everyone likes—{A} or {B}?",
	"You need someone to keep track of wins—{A} or {B}?",
	"Choosing a quick warm-up game—{A} or {B}?"
  ];
  
